// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAisDXA_GsY8v2YTowWSpJ5_zHbKyTjroQ',
    appId: '1:558373899791:web:3167be556327e8ae811d7a',
    messagingSenderId: '558373899791',
    projectId: 'trening-app-89bf5',
    authDomain: 'trening-app-89bf5.firebaseapp.com',
    storageBucket: 'trening-app-89bf5.appspot.com',
    measurementId: 'G-LBH41M2JM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE3GLGMWXQclc7jp72PjswYrFlgXWv7EY',
    appId: '1:558373899791:android:ad4716a020874748811d7a',
    messagingSenderId: '558373899791',
    projectId: 'trening-app-89bf5',
    storageBucket: 'trening-app-89bf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNEP50wsjLtkgsy6frUvZenQJ40rUrEBQ',
    appId: '1:558373899791:ios:aa4c7da5d7a108a0811d7a',
    messagingSenderId: '558373899791',
    projectId: 'trening-app-89bf5',
    storageBucket: 'trening-app-89bf5.appspot.com',
    iosClientId: '558373899791-l2id7s9jqpg5fabhllf51d7p554q9llc.apps.googleusercontent.com',
    iosBundleId: 'com.example.treningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNEP50wsjLtkgsy6frUvZenQJ40rUrEBQ',
    appId: '1:558373899791:ios:aa4c7da5d7a108a0811d7a',
    messagingSenderId: '558373899791',
    projectId: 'trening-app-89bf5',
    storageBucket: 'trening-app-89bf5.appspot.com',
    iosClientId: '558373899791-l2id7s9jqpg5fabhllf51d7p554q9llc.apps.googleusercontent.com',
    iosBundleId: 'com.example.treningApp',
  );
}
